version: '2'
services:
  web:
    image: odoo:9.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./data/web:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/db:/var/lib/postgresql/data/pgdata
